// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WebApplication1.Models
{
    public partial class sqltestContext : DbContext
    {
        public sqltestContext()
        {
        }

        public sqltestContext(DbContextOptions<sqltestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MockData> MockData { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MockData>(entity =>
            {
                entity.HasKey(e => e.Hn)
                    .HasName("PK__MOCK_DAT__3213C0C6DC374D55");

                entity.ToTable("MOCK_DATA");

                entity.Property(e => e.Hn)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("hn");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("email");

                entity.Property(e => e.FirstName)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("first_name");

                entity.Property(e => e.LastName)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("last_name");

                entity.Property(e => e.Phone)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("phone");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}